// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getfeedviaurl.sql

package database

import (
	"context"
)

const getFeedViaUrl = `-- name: GetFeedViaUrl :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at 
FROM feeds
WHERE url = $1
`

func (q *Queries) GetFeedViaUrl(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedViaUrl, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
